name: tichodose
description: "A new Flutter project."
publish_to: 'none'
version: 0.3.0+13

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_phoenix: "^1.0.0"
  function_tree: ^0.9.1
  provider: ^6.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/playstore.png"

flutter:
  uses-material-design: true
